### ISSUE TITLE
Prefill visibility, markdown, and image

### ISSUE THREAD

**Issue by carsonmclean** [CMPUT404F16T04/sturdy-octo-computing-machine#55]
- [x] markdown
- [x] Visibility

**Comment by kobitoko** [comment]
This is for Post Edit right?
If so, https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/commit/2667c76b929c8a9e2bc348b040b86916b29fd406 did the markdown visibility, and I don't think image need to be prefilled, because just pressed when user wants new image (the old id just stays in the post model otherwise).

**Comment by carsonmclean** [comment]
Finished Visibility prefill in 20647a74335d42
